config/routes.rb
Getajob::Application.routes.draw do

  get "companies/index"

  get "employee/notepad"

  get "employer/index"

  root :to => "listings#new"

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' } do
    match '/users/sign_up/:company' => 'registrations#new'
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  match 'companies/positions' => 'companies#positions', :as => :"positions"
  resources :companies do
    resources :positions
  end

  resources :listings

  resource :cv, :only => [:new, :create, :destroy]
  match 'cv/add_experience' => 'cvs#add_experience', :as => :add_experience
  match 'cv/:id' => 'cvs#show', :as => :cv_route

  match 'users/update/user_details' => 'users#update_user_details', :as => :user_details

  match 'employee/notepad' => 'employee#notepad', :as => :employee_notepad  
  match 'employee/cv' => 'employee#cv_list', :as => :employee_cv_list
  match 'employee/details' => 'employee#details', :as => :employee_details
  match 'employee/bookmarks' => 'employee#bookmarks', :as => :employee_bookmarks
  match 'employee/calendar' => 'employee#calendar', :as => :employee_calendar

end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  respond_to :html, :js, :json

  def notepad
    @cvs = current_user.cvs
  end

  def cv_list
    @cvs = current_user.cvs
  end

  def details
    @detail = current_user.user_detail
  end

  def calendar

  end

end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employee/_employee_sidebar.html.erb
<ul class="unstyled">
  <li><%= link_to t("employee.sidebar.data"), employee_details_path, :remote => true %></li>
  <li><%= link_to t("employee.sidebar.cv"), employee_cv_list_path, :remote => true %></li>
  <li><%= link_to t("employee.sidebar.bookmarks"), employee_bookmarks_path, :remote => true %></li>
  <li><%= link_to t("employee.sidebar.calendar"), employee_calendar_path, :remote => true %></li>
  <li><%= link_to t("shared.nav.empoyee.search"), '#' %></li>
</ul>

app/views/employee/_table_cvs.html.erb
<div class="row">
  <div class="span5"><h1>Мои резюме</h1></div>
  <div class="span3"><%= link_to t(:new_cv), new_cv_path, :class => "btn primary" %></div>
</div>
<div class="cv_list">
  <table class="condensed-table">
    <thead>
      <tr>
        <th>Статистика</th>
        <th>Резюме</th>
        <th>Дата</th>
        <th>Статус на сайте</th>
        <th>Личные данные</th>
      </tr>
    </thead>
    <tbody>
      <% @cvs.each do |cv| %>
        <tr data-id="<%=cv.id%>">
          <td><%= nil %></td>
          <td><%= link_to cv.title, cv_route_path(cv.id) %></td>
          <td><%= cv.updated_at %></td>
          <td><%= cv.active ? "Доступно" : "Скрыто" %></td>
          <td><%#= link_to 'delete', company_position_path(current_user.company,p), :confirm=> 'Are you sure?', :method => :delete, :remote=> true, 'data-type'=>'json' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employee/bookmarks.js.erb
$("body.persona .container .contents .row .span12").empty();
$("body.persona .container .contents .row .span12").append("<h3>Мои закладки</h3>");

app/views/employee/calendar.js.erb
$("body.persona .container .contents .row .span12").empty();
$("body.persona .container .contents .row .span12").append("<h3>Календарь будет здесь! Круто, правда? :)</h3>");

app/views/employee/cv_list.js.erb
$("body.persona .container .contents .row .span12").empty();
$("body.persona .container .contents .row .span12").append("<%= escape_javascript(render :partial => 'table_cvs' )%>");
//initDeleteLinks();

app/views/employee/details.js.erb
$("body.persona .container .contents .row .span12").empty();
$("body.persona .container .contents .row .span12").append("<h3>Мои данные</h3>");
//$("body.persona .container .contents .row .span12").append("<%#= escape_javascript(render :partial => 'table_cvs' )%>");
//initDeleteLinks();

app/views/employee/notepad.html.erb
<div class="span3">
    <%= render :partial => "employee_sidebar" %>
</div>
<div class="span12">
    <%= render :partial => "table_cvs" %>
</div>