config/routes.rb
Getajob::Application.routes.draw do

  get "companies/index"

  get "employee/notepad"

  get "employer/index"

  root :to => "listings#new"

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' } do
    match '/users/sign_up/:company' => 'registrations#new'
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  match 'companies/positions' => 'companies#positions', :as => :"positions"
  resources :companies do
    resources :positions
  end

  resources :listings

  resource :cv, :only => [:new, :create, :destroy]
  match 'cv/add_experience' => 'cvs#add_experience', :as => :add_experience
  match 'cv/:id' => 'cvs#show', :as => :cv_route

  match 'users/update/user_details' => 'users#update_user_details', :as => :user_details

  match 'employee/notepad' => 'employee#notepad', :as => :employee_notepad  
  match 'employee/cv' => 'employee#cv_list', :as => :employee_cv_list
  match 'employee/details' => 'employee#details', :as => :employee_details
  match 'employee/bookmarks' => 'employee#bookmarks', :as => :employee_bookmarks
  match 'employee/calendar' => 'employee#calendar', :as => :employee_calendar

end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :company
  has_and_belongs_to_many :regions, :validate => true
  has_and_belongs_to_many :busynesses
  has_and_belongs_to_many :spheres

  accepts_nested_attributes_for :regions
  accepts_nested_attributes_for :busynesses
  accepts_nested_attributes_for :spheres

  validates :title, :presence => true
  validates :description, :presence => true
  validates :regions, :presence => true
  validates :spheres, :presence => true
  validates :busynesses, :presence => true

  def status
    active ? I18n.t(:"positions.status.active") : I18n.t(:"positions.status.nonactive") 
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_filter :authenticate_user!, :except => :show

  def show
    @position = current_user.company.positions.find(params[:id])
  end

  def new
    @position = current_user.company.positions.build
    @spheres = Sphere.all
    @busynesses = Busyness.all
    @managers = current_user.company.managers
  end

  def create
    @position = current_user.company.positions.new(params[:position])
    if @position.save
      flash[:notice] = "Successfully created position."
      redirect_to company_position_url(@position.company_id, @position)
    else
      @spheres = Sphere.all
      @busynesses = Busyness.all
      @managers = current_user.company.managers
      render :new
    end
  end

  def update
  end

  def destroy
    @position = current_user.company.positions.find(params[:id])
      respond_to do |format|
        if @position.destroy
          format.js { render :json => {:status => :success, :position_id => @position.id}}
        else
          format.js { render :json => {:status => :failed}}
        end
      end
  end

  def activate
  end

  def deactivate
  end

end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/activate.html.erb
<h1>Positions#activate</h1>
<p>Find me in app/views/positions/activate.html.erb</p>

app/views/positions/deactivate.html.erb
<h1>Positions#deactivate</h1>
<p>Find me in app/views/positions/deactivate.html.erb</p>

app/views/positions/index.html.erb
<div class="span9">
  <h2>Мои вакансии</h2>
</div>
<div class="span6">
  <div><%= link_to 'Добавить вакансию', new_company_position_path, :class => "btn success" %></div>
</div>

app/views/positions/new.html.erb
<div class="span16">
  <h1><%= t(:"positions.new.add_new_position") %></h1>


  <%= simple_form_for @position, :url => company_positions_path, :defaults => {:class => "form-stacked"} do |f| %>
      <fieldset>
        <legend>Общая
          информация&nbsp;&nbsp;<span class="label notice"><%= link_to "помощь", '#', :class => "helper" %></span>
        </legend>
        <%= f.input :title, :label => I18n.t('positions.new.title'), :input_html => {:class=> "xlarge"}, :required => false %>

        <div class="clearfix"></div>
        <div class="row spheres">
          <div class="span7">
            <ul class="inputs-list">
              <% @spheres.each do |sphere| %>
                  <% if sphere.id < 15 %>
                      <li>
                        <label>
                          <input type="checkbox" name="position[sphere_ids][]" value="<%= sphere.id %>">
                          <span><%= sphere.title %></span>
                        </label></li>
                  <% end %>
              <% end %>
            </ul>
          </div>
          <div class="span7">
            <ul class="inputs-list">
              <% @spheres.each do |sphere| %>
                  <% if sphere.id > 15 %>
                      <li><label>
                        <input type="checkbox" name="position[sphere_ids][]">
                        <span><%= sphere.title %></span>
                      </label></li>
                  <% end %>
              <% end %>
            </ul>
          </div>
        </div>

      </fieldset>


      <fieldset>
        <legend>Требования к
          соискателю&nbsp;&nbsp;<span class="label notice"><%= link_to "помощь", '#', :class => "helper" %></span>
        </legend>
        <div class="clearfix"></div>
        <%= f.association :regions, :label => I18n.t('positions.new.regions'), :as => :select, :input_html => {:multiple => false, :size => 1, :class => :xlarge}, :required => false %> 
      </fieldset>

      <fieldset>
        <%= f.input :salary, :label => I18n.t("positions.new.salary"), :input_html => {:class => :xlarge}, :required => false %>
      </fieldset>

      <fieldset>
        <div class="clearfix">
          <div class="span7">
            <ul class="inputs-list busynesses">
              <% @busynesses.each do |bu| %>
                  <% if bu.id < 15 %>
                      <li>
                        <label>
                          <input type="checkbox" name="position[busyness_ids]" value="<%= bu.id %>">
                          <span><%= bu.role %></span>
                        </label></li>
                  <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <%= f.label :education_id %>
        <%= f.text_field :education_id %>
      </fieldset>


      <fieldset>
        <legend>Описание вакансии*
          <span class="help-block">Помните, чем подробнее Вы опишете Вашу вакансию, тем меньше времени потратите впоследствии при собеседованиях с неподходящими кандидатами.
          </span>
        </legend>

        <div class="clearfix">
          <%= f.input :description, :label => I18n.t('positions.new.description'),
                      :as => :text, :input_html => {:class => 'xxlarge', :rows => 10, :cols => 40, :maxlength => 10}, :required => false %>
          <span class="help-block">
                <strong>!</strong> не более 3000 символов
              </span>
        </div>
      </fieldset>

      <fieldset>
        <legend>Контактная информация</legend>
        <div class="clearfix">
          <label class="select optional" for="position_user_id">Менеджер:</label>
          <select id="position_user_id" class="select optional xlarge" size=1 name="position[user_id]">
            <% @managers.each do |value, name| %>
              <option value="<%=value %>"><%=name%></option>
            <% end %>
          </select>
        </div>
      </fieldset>

      <fieldset>
        <legend>Размещение вакансии</legend>
        <div class="clearfix"><div class="span5">
          <ul class="inputs-list active">
            <li><label><input type="radio" value="true" name="position[active]"><span>Активная</span></li>
            <li><label><input type="radio" value="false" name="position[active]"><span>Неактивная</span></li>
          </ul>
        </div></div>  
      </fieldset>

      <div class="actions">
        <%= f.submit "Сохранить", :class=> "btn primary" %>
      </div>
  <% end %>
</div>

app/views/positions/show.html.erb
<div class="span9">
  <h2><%= @position.title %></h2>
  <p>описание:<%= @position.description %></p>
</div>
<div class="span6">
  <div><%= link_to 'Добавить вакансию', new_company_position_path, :class => "btn success" %></div>
</div>