config/routes.rb
Getajob::Application.routes.draw do

  get "companies/index"

  get "employee/notepad"

  get "employer/index"

  root :to => "listings#new"

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' } do
    match '/users/sign_up/:company' => 'registrations#new'
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  match 'companies/positions' => 'companies#positions', :as => :"positions"
  resources :companies do
    resources :positions
  end

  resources :listings

  resource :cv, :only => [:new, :create, :destroy]
  match 'cv/add_experience' => 'cvs#add_experience', :as => :add_experience
  match 'cv/:id' => 'cvs#show', :as => :cv_route

  match 'users/update/user_details' => 'users#update_user_details', :as => :user_details

  match 'employee/notepad' => 'employee#notepad', :as => :employee_notepad  
  match 'employee/cv' => 'employee#cv_list', :as => :employee_cv_list
  match 'employee/details' => 'employee#details', :as => :employee_details
  match 'employee/bookmarks' => 'employee#bookmarks', :as => :employee_bookmarks
  match 'employee/calendar' => 'employee#calendar', :as => :employee_calendar

end

app/views/shared/_action.html.erb
<div class="navbar navbar-fixed-top"><div class="navbar-inner">
  <div class="container">
    <%= link_to "айРаботка", root_path, :class=> :brand %>
    <div class="nav-collapse">
    <ul class="nav">
      <% if user_signed_in? %>
  		<li><%= link_to current_user.email, edit_user_registration_path %></li>
		<li><%= link_to t('shared.nav.logout'), destroy_user_session_path, :method=>'delete' %></li>
	<% else %>
		<li><%= link_to t('shared.nav.login'), new_user_session_path, :id => "sign-in" %></li>
		<li class="menu">
			<%= link_to t('shared.nav.sign_up'), '#', :class => 'menu' %>
				<li><%= link_to t('shared.nav.for_candidate'), new_user_registration_path %></li>
				<li><%= link_to t('shared.nav.for_company'), '/users/sign_up/company' %></li>
		</li>
  	<% end%>
    </ul></div>
  </div>
</div></div>

app/views/shared/_masthead.html.erb
<header class="jumbotron masthead" id="overview">
  <div class="inner">
    <div class="container">
      <div class="span9 search">
      <%= form_tag 'positions/search', :class => "well form-search", :remote => true do -%>
          <div class="search_area">
            <%= text_field_tag 'position', nil, :placeholder=> "ВВЕДИТЕ ДОЛЖНОСТЬ", :class=> :"search-query" %>
          </div>
      <% end -%>
      </div>
    </div>
    <!-- /container -->
    <ul id="siteNav">
      <% if current_user %>
        <% if current_user.is_company? %>
          <li>
            <%= link_to t("shared.nav.company.my_items"), positions_path, :remote => true %>
          </li>
          <li><%= link_to t("shared.nav.company.responces"), "#" %></li>
          <li><%= link_to t("shared.nav.company.agents"), "#" %></li>
          <li><%= link_to t("shared.nav.company.goods"), "#" %></li>
        <% else %>
          <li><%= link_to t("shared.nav.empoyee.notepad"), employee_notepad_path %></li>
          <li><%= link_to t("shared.nav.empoyee.messages"), "#" %></li>
          <li><%= link_to t("shared.nav.empoyee.search"), "#" %></li>
          <li><%= link_to t("shared.nav.empoyee.settings"), "#" %></li>
          <li><%= link_to t("shared.nav.empoyee.blog"), "#" %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_navigation.html.erb
<ul class="nav">
  <% if user_signed_in? && current_user.is_company %>
      <li><%= link_to t("shared.nav.my_items"), company_positions_path(current_user) %></li>
      <li><%= link_to t("shared.nav.responces"), "#" %></li>
      <li><%= link_to t("shared.nav.agents"), "#" %></li>
      <li><%= link_to t("shared.nav.goods"), "#" %></li>
  <% elsif user_signed_in? %>
      <li><%= link_to current_user.email, edit_user_registration_path %></li>
      <li><%= link_to t('shared.nav.logout'), destroy_user_session_path, :method=>'delete' %></li>
  <% else %>
      <li><%= link_to t('shared.nav.login'), new_user_session_path %></li>
      <li class="menu">
        <%= link_to t('shared.nav.sign_up'), '#', :class => 'menu' %>
        <ul class="menu-dropdown">
          <li><%= link_to t('shared.nav.for_candidate'), new_user_registration_path %></li>
          <li><%= link_to t('shared.nav.for_company'), '/users/sign_up/company' %></li>
        </ul>
      </li>
  <% end %>
</ul>

app/views/shared/_vk_button.html.erb
<div class="social-signin">
<%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to omniauth_authorize_path(resource_name, provider), :class => "vk" do %>
        <div></div>
        В Контакте
    <% end -%>
<% end -%>

</div>