config/routes.rb
Getajob::Application.routes.draw do

  get "companies/index"

  get "employee/notepad"

  get "employer/index"

  root :to => "listings#new"

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' } do
    match '/users/sign_up/:company' => 'registrations#new'
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  match 'companies/positions' => 'companies#positions', :as => :"positions"
  resources :companies do
    resources :positions
  end

  resources :listings

  resource :cv, :only => [:new, :create, :destroy]
  match 'cv/add_experience' => 'cvs#add_experience', :as => :add_experience
  match 'cv/:id' => 'cvs#show', :as => :cv_route

  match 'users/update/user_details' => 'users#update_user_details', :as => :user_details

  match 'employee/notepad' => 'employee#notepad', :as => :employee_notepad  
  match 'employee/cv' => 'employee#cv_list', :as => :employee_cv_list
  match 'employee/details' => 'employee#details', :as => :employee_details
  match 'employee/bookmarks' => 'employee#bookmarks', :as => :employee_bookmarks
  match 'employee/calendar' => 'employee#calendar', :as => :employee_calendar

end

app/models/cv.rb
#  create_table "cvs", :force => true do |t|
#    t.string   "title"
#    t.integer  "user_id"
#    t.integer  "salary"
#    t.boolean  "expirience"
#    t.text     "info"
#    t.boolean  "status"
#    t.datetime "created_at"
#    t.datetime "updated_at"
#  end

class Cv < ActiveRecord::Base
  belongs_to :user
  has_many :experience, :dependent => :destroy, :class_name => 'Experience'
  has_many :education, :dependent => :destroy, :class_name => 'Education'
  has_many :training, :dependent => :destroy, :class_name => 'Training'

  accepts_nested_attributes_for :experience, :allow_destroy => true
  accepts_nested_attributes_for :education, :allow_destroy => true
  accepts_nested_attributes_for :training, :allow_destroy => true
#  attr_accessible :title, :salary, :experiences, :status, :info

  acts_as_taggable_on :skills

  validates :title, :presence => true
#  validates :expirience, :presence => true //TODO impossible to submit form even if expirience is specified.
  validates :active, :presence => true
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @user_detail =  current_user.build_user_detail unless current_user.have_user_detail?
    @cv = current_user.cvs.build
    @cv.experience.build
    @cv.education.build
    @cv.training.build
  end

  def create
    @cv = current_user.cvs.build(params[:cv])
    if @cv.save
      redirect_to cv_route_path @cv.id
    else
      render :new
    end
  end

  def show 
    @cv = current_user.cvs.find(params[:id])  
  end

  def add_experience
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/views/cvs/_education.html.erb
<div class="new_education_part">
  <div class="clearfix">
    <%= f.label :level, t("cv.education.level") %>
    <div class="input"><%= f.text_field :level %><span class="help-inline"></span></div>
  </div>
  <div class="clearfix">
    <%= f.label :name, t("cv.education.name") %>
    <div class="input"><%= f.text_field :name %><span class="help-inline"></span></div>
  </div>

  <div class="clearfix">
    <%= f.label :faculty, t("cv.education.faculty") %>
    <div class="input"><%= f.text_field :faculty %><span class="help-inline"></span></div>
  </div>

  <div class="clearfix">
    <%= f.label :city, t("cv.education.city") %>
    <div class="input"><%= f.text_field :city %><span class="help-inline"></span></div>
  </div>

  <div class="clearfix">
    <%= f.label :date_start, t("cv.education.time_period") %>
    <div class="input"><%= f.text_field :date_start, :class => :datepicker %> по <%= f.text_field :date_end, :class => :datepicker %>
      <span class="help-inline"></span>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :description, t("cv.experience.description") %>
    <div class="input"><%= f.text_area :description, :size => "20x7", :class => :xxlarge %>
      <span class="help-inline"></span>
    </div>
  </div>

  <p> <%= remove_child_link "убрать", f %> </p>
</div>

app/views/cvs/_experience.html.erb
<div class="new_experience_part">
  <div class="clearfix">
    <%= f.label :company, t("cv.experience.company_name") %>
    <div class="input">
      <%= f.text_field :company %>
      <span class="help-inline"></span>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :city, t("cv.experience.city") %>
    <div class="input">
      <%= f.text_field :city %><span class="help-inline"></span>
    </div>
  </div>
  
  <div class="clearfix">
    <%= f.label :position, t("cv.experience.position") %>
    <div class="input">
      <%= f.text_field :position %>
      <span class="help-inline"></span>
    </div>
  </div>
  
  <div class="clearfix">
    <%= f.label :date_start, t("cv.experience.time_period") %>
    <div class="input">
      <%= f.text_field :date_start, :class => :datepicker %> по <%= f.text_field :date_end, :class => :datepicker %>
      <span class="help-inline"></span>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :description, t("cv.experience.description") %>
    <div class="input">
      <%= f.text_area :description, :size => "20x7", :class => :xxlarge %>
      <span class="help-inline"></span>
    </div>
  </div>

  <p> <%= remove_child_link "убрать", f %> </p>
</div>

app/views/cvs/_training.html.erb
<div class="new_training_part">
  <div class="clearfix">
    <%= f.label :institution, t("cv.training.institution") %>
    <div class="input"><%= f.text_field :institution %><span class="help-inline"></span></div>
  </div>
  <div class="clearfix">
    <%= f.label :course, t("cv.training.course") %>
    <div class="input"><%= f.text_field :course %><span class="help-inline"></span></div>
  </div>

  <div class="clearfix">
    <%= f.label :date_start, t("cv.training.date_start") %>
    <div class="input"><%= f.text_field :date_start %><span class="help-inline"></span></div>
  </div>

  <div class="clearfix">
    <%= f.label :date_end, t("cv.training.date_end") %>
    <div class="input"><%= f.text_field :date_end %><span class="help-inline"></span></div>
  </div>

  <p> <%= remove_child_link "remove training", f %> </p>
</div>

app/views/cvs/add_experience.js.erb
$('fieldset#experience').append(<%= escape_javascript(render :partial => 'experience' )%>);

app/views/cvs/new.html.erb
<% if @user_detail %>
    <%= form_for @user_detail, :url => :user_details, :validate => true, :remote => true do |f| %>
        <fieldset>
          <legend>Личные данные</legend>
          <div class="clearfix"><%= f.label :first_name %><%= f.text_field :first_name, :class=> :xlarge %></div>
          <div class="clearfix"><%= f.label :last_name %><%= f.text_field :last_name, :class=> :xlarge %></div>
          <div class="clearfix"><%= f.label :phone %><%= f.text_field :phone, :class => :xlarge %></div>
          <div class="clearfix">
            <%= f.label :birthday %>
            <%= f.date_select("birthday", :order => [:year, :month, :day],
                              :start_year => 1970,
                              :prompt => {:day => 't day', :month => 'Select month', :year => 'Select year'}, :class => :mini) %>
          </div>
          <div class="clearfix"><%= f.label :city %><%= f.text_field :city %></div>
          <div class="actions">
            <%= f.submit 'Next', :class=> "btn primary" %>
          </div>
        </fieldset>
    <% end %>
<% end %>

<div class="<%= 'inactive' if @user_detail %> new_cv_wrapper">
  <%= form_for @cv, :url => cv_path, :validate => true, :html => {:class => "form-stacked"} do |f| %>
      <fieldset>
        <legend>Общая информация</legend>
        <div class="clearfix">
          <%= f.label :title, 'Заголовок резюме' %>
          <div class="input">
            <%= f.text_field :title, :class => :span7 %>
            <span class="help-inline"></span>
          </div>
        </div>

        <div class="clearfix">
          <%= f.label t(:salary) %>
          <div class="input">
            <%= f.text_field :salary, :class => :xlarge %>
          </div>
        </div>
      </fieldset>


      <fieldset id="experience">
        <legend><%= t(:experience) %></legend>
        <div class="clearfix">
          <%= f.fields_for :experience do |experience| %>
              <%= render :partial => "experience", :locals => {:f => experience} %>
          <% end %>
        </div>
        <p><%= add_child_link "добавить опыт", :experience %></p>


        <%= new_child_fields_template f, :experience %>


      </fieldset>

      <fieldset>
        <legend><%= t(:education) %></legend>
        <div class="clearfix">
          <%= f.fields_for :education do |education| %>
            <%= render :partial => 'education', :locals => {:f => education} %>
          <% end %>
        </div>

        <p><%= add_child_link "добавить место учебы", :education %>
        <%= new_child_fields_template f, :education %>
      </fieldset>

      <fieldset>
        <legend><%= t(:training) %></legend>
        <div class="clearfix">
          <%= f.fields_for :training do |training| %>
            <%= render :partial => 'training', :locals => {:f => training} %>
          <% end %>          
        </div>
        <p><%= add_child_link "добавить тренинг", :training %>
        <%= new_child_fields_template f, :training %>
      </fieldset>

      <fieldset>
        <legend>Дополнительная информация о Вас</legend>

        <div class="clearfix">
          <%= f.label :description %>
          <div class="input">
            <%= f.text_field :description, :class => :xlarge %>
          </div>
        </div>
      </fieldset>
      
      <fieldset>
        <legend>Тэги</legend>
        <div class="clearfix">
          <%= f.label :skill_list %>
          <div class="input"><%= f.text_field :skill_list, :class => :xlarge %></div>
        </div>
      </fieldset>

      <fieldset>
        <legend>Статус резюме</legend>
        <div class="clearfix">
          <div class="span5">
            <ul class="inputs-list active">
              <li><label><input type="radio" value="true" name="cv[active]"><span>Активная</span></label></li>
              <li><label><input type="radio" value="false" name="cv[active]"><span>Неактивная</span></label></li>
            </ul>
          </div>
        </div>
      </fieldset>

      <div class="actions">
        <%= f.submit "Сохранить", :class=> "btn primary" %>
      </div>
  <% end %>

</div>

app/views/cvs/show.html.erb
<div class="cv_wrapper">
  <div class="sf"><span class="">резюме от <%= @cv.updated_at %></span></div>
  <h1 class="name"><%= @cv.user.full_name %></h1>

  <h3><%= @cv.title %>
    <small><%= @cv.job_type %></small></h3>

  <div class="contacts">
    <h3 class="underline">Личные данные</h3>
    <table>
      <tr>
        <td>тел</td>
        <td><%= @cv.user.user_detail.phone %></td>
      </tr>
      <tr>
        <td>мыло</td>
        <td><%= @cv.user.email %></td>
      </tr>
      <tr>
        <td>место проживания</td>
        <td><%= @cv.user.user_detail.city %></td>
      </tr>
    </table>
  </div>

  <div class="work_experiences">
    <h3 class="underline">Опыт работы</h3>
    <% @cv.experience.each do |item| %>
        <div id="exp_<%= item.id %>" class="experience_item">
          <h4><%= item.company %> &nbsp;&nbsp;&nbsp;<span>c <%= item.date_start %> по <%= (item.date_end.nil?? "наст. время " : item.date_end) %></span></h4>
          <h5><%= item.position %></h5>
          <div><%= item.description %></div>
        </div>
    <% end %>
  </div>

  <div class="educations">
    <h3 class="underline">Образование</h3>
    <% @cv.education.each do |edu| %>
        <div id="edu_<%= edu.id %>" class="education_item">
          <h5><%= edu.name %> - <%= edu.city %></h5>

          <div><%= edu.faculty %></div>
          <div><%= edu.description %></div>
        </div>
    <% end %>
  </div>

  <div class="tags">
    <h6>тэги этого резюме</h6>
    <%- @cv.skill_list.each do |skill| %>
        <span class="label"><%= skill %></span>
    <%- end %>
  </div>
</div>